# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-05 16:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flavor', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('manufacturedDate', models.DateTimeField(default=datetime.datetime(2018, 6, 5, 16, 37, 4, 818089, tzinfo=utc), verbose_name='MFD')),
                ('bestBefore', models.DateTimeField(blank=True, null=True, verbose_name='BB')),
            ],
        ),
    ]
